### ISSUE TITLE
Dynamic resize

### ISSUE THREAD

**Issue by hampfh** [Hampfh/Conhics#1]
Conhics need to be able to change it's buffer when the window is resized

**Comment by haholm** [comment]
How about detecting a resize before writing to the console buffer? Will the application still crash regardless, whether you write to it/flush or not when the window is resized?

**Comment by hampfh** [comment]
That could be it, however, the tricky part is that the resize event can be triggered at any time since it only requires the user to drag the window.

What makes the application crash is writing outside the buffer which happens when the user shrinks the window.
I think the core problem is that conhics relies on an array as it's virtual window, resulting in problems as arrays aren't resizable. We could use lists but that would allocate unnecessary memory

**Comment by haholm** [comment]
In that case, checking if the console window was resized before trying to write to the console buffer would work, no? And subsequently resize the buffer.

**Comment by hampfh** [comment]
Yea that seems reasonable, my problem is the resize part. It seems like it sometimes does not work and the console throws exceptions 

![image](https://user-images.githubusercontent.com/30767818/86530854-a8012d80-bebc-11ea-8aa0-eac97c2606d7.png)
![image](https://user-images.githubusercontent.com/30767818/86530855-ae8fa500-bebc-11ea-9a0d-edf6f630fb2b.png)

These two errors are linked to the following code:
![image](https://user-images.githubusercontent.com/30767818/86530864-c109de80-bebc-11ea-9e46-97f4fb2972ed.png)

**Comment by hampfh** [comment]
I believe I have found a solution to this here: https://stackoverflow.com/questions/31467941/resize-event-for-console
